/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package products;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import log.*;

import static products.Cart.c;

/**
 *
 * @author mariabrad
 */
public class Prod extends javax.swing.JFrame {
   private String p;
  
    /**
     * Creates new form Prod
     */
    public Prod(String produs) {
        p=produs;
        
        initComponents();
           try {
             ProductTable table=new ProductTable();
             ResultSet result = table.create(p);
             if(result.next()){
                 Product ex=new Product(result.getString("id"),p,result.getString("descriere"),result.getString("expirare"),result.getString("prescriptie"),result.getString("ingredient"),result.getString("pret"));
                  txtdesc.setText(result.getString("descriere"));
                  txtexp.setText(result.getString("expirare"));
                  txtingr.setText(result.getString("ingredient"));
                  txtnume.setText(produs);
                  txtpr.setText(result.getString("prescriptie"));
                  txtpret.setText(result.getString("pret"));
                 
           
            }
            else{
              JOptionPane.showMessageDialog(this,"The product you entered doesn't exist!");
                
            }
             } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
      
        } catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }
    
   

    /**
     * This method is called from within the constructor to the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnume = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        txtexp = new javax.swing.JTextField();
        txtpr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtingr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpret = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        txtnume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnume);
        txtnume.setBounds(200, 23, 340, 37);
        getContentPane().add(txtdesc);
        txtdesc.setBounds(126, 124, 187, 180);
        getContentPane().add(txtexp);
        txtexp.setBounds(494, 124, 187, 26);
        getContentPane().add(txtpr);
        txtpr.setBounds(494, 162, 187, 26);

        jLabel3.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jLabel3.setText("Descriere");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 124, 59, 29);

        jLabel1.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jLabel1.setText("Expirare");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 130, 70, 29);

        jLabel2.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jLabel2.setText("Prescriptie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(392, 167, 80, 29);

        txtingr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingrActionPerformed(evt);
            }
        });
        getContentPane().add(txtingr);
        txtingr.setBounds(494, 194, 187, 26);

        jLabel4.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jLabel4.setText("Ingredient");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 200, 90, 29);
        getContentPane().add(txtpret);
        txtpret.setBounds(494, 226, 187, 26);

        jLabel5.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jLabel5.setText("Pret");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(396, 231, 80, 29);

        jButton1.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 6, 82, 37);

        jButton2.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jButton2.setText("Add to cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(494, 315, 118, 37);

        jLabel6.setFont(new java.awt.Font("Savoye LET", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mariabrad/Anul II/SEM II/FIS/Log/Log/Images/back2.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 810, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtingrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingrActionPerformed

    private void txtnumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                     Home orrd=new Home();
                     this.setVisible(false);
                     orrd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               try {
             
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection connection =DriverManager.getConnection("jdbc:mysql://localhost/Credentials?useLegacyDatetimeCode=false&serverTimezone=Europe/Bucharest","root","M!lkdrink");
             PreparedStatement ps = connection.prepareStatement("SELECT * FROM `produse` WHERE `nume` = ? OR  `ingredient` = ?");
             ps.setString(1,p);
             ps.setString(2,p);
             ResultSet result = ps.executeQuery();
             if(result.next()){
                
              Product ex=new Product(result.getString("id"),p,result.getString("descriere"),result.getString("expirare"),result.getString("prescriptie"),result.getString("ingredient"),result.getString("pret"));
              c.add(ex);
             
           
            }
            else{
              JOptionPane.showMessageDialog(this,"The product you entered doesn't exist!");
                
            }
             } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
      
        } catch (SQLException ex) {
            Logger.getLogger(Prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prod("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtexp;
    private javax.swing.JTextField txtingr;
    private javax.swing.JTextField txtnume;
    private javax.swing.JTextField txtpr;
    private javax.swing.JTextField txtpret;
    // End of variables declaration//GEN-END:variables
}
